// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOL9gZLyaZLCISRDsrmxcWHKL4dNd6suw',
    appId: '1:50391082248:web:a74f0b83b19b283f11b8bd',
    messagingSenderId: '50391082248',
    projectId: 'done-task-app',
    authDomain: 'done-task-app.firebaseapp.com',
    storageBucket: 'done-task-app.appspot.com',
    measurementId: 'G-47ZP88Y2RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaSBbJ8Pxf2Do-5SmLPHWJRWMrp9Zq8Lk',
    appId: '1:50391082248:android:ea3709a7808aae1911b8bd',
    messagingSenderId: '50391082248',
    projectId: 'done-task-app',
    storageBucket: 'done-task-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpYuDGd3CFpiraiGCK4NNFQwPJvcKg1vQ',
    appId: '1:50391082248:ios:a4c35d980e36564811b8bd',
    messagingSenderId: '50391082248',
    projectId: 'done-task-app',
    storageBucket: 'done-task-app.appspot.com',
    iosClientId: '50391082248-j5lb82bara9t0bmm9rav7224nc1he2l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpYuDGd3CFpiraiGCK4NNFQwPJvcKg1vQ',
    appId: '1:50391082248:ios:a4c35d980e36564811b8bd',
    messagingSenderId: '50391082248',
    projectId: 'done-task-app',
    storageBucket: 'done-task-app.appspot.com',
    iosClientId: '50391082248-j5lb82bara9t0bmm9rav7224nc1he2l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
